# Generated by Django 2.2.12 on 2021-10-19 07:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('publictax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='check_alotax',
            field=otree.db.models.FloatField(blank=True, null=True),
        ),
    ]
