# Generated by Django 2.2.12 on 2021-10-21 17:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('publictax', '0002_player_check_alotax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='FL5',
            field=otree.db.models.IntegerField(choices=[[1, 'More than today'], [2, 'Exactly the same'], [3, 'Less than today'], [4, "I don't know"]], null=True, verbose_name='Suppose that in the year 2030, your income has doubled, and prices of all goods have doubled too. In 2030, how much will you be able to buy with your income?'),
        ),
    ]
